# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 754dedd6d0b157568da7954afaec2ae1397bd187d19792938aa8131b0487dbc0798179551dd25dbf08ebd0cb5f22bf87c07bd836a3533082f9c191aeb522ca32

test:
  secret_key_base: 727ec381c49b660319454625f7ab6ebe7ff47d003720f0a1999d7c03b08ea38ac4a54d2e56d3e7815b1cdb1c23032428497e4f35adc6fb111efd1d785ee39b25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
